FROM node:16-alpine
RUN apk add --no-cache python3 make g++

ENV NODE_ENV=development

# Create app directory
RUN mkdir -p /usr/dnp/insurance-zalo-mini-app
WORKDIR /usr/dnp/insurance-zalo-mini-app

# Installing dependencies
COPY package.json /usr/dnp/insurance-zalo-mini-app/
RUN yarn install --network-timeout 1000000

# Copying source files
COPY . /usr/dnp/insurance-zalo-mini-app
EXPOSE 2999

# Running the app
CMD ["yarn","dev"]